@if(count($savedfiles) < 1)
    <div class="flex items-center gap-x-2">
    {{__("Generate subtitling")}}
        <!-- Smaller Switch -->
        <label for="hs-xs-switch-autosub" class="relative inline-block w-8 h-4 cursor-pointer">
            <input type="checkbox" id="hs-xs-switch-autosub" class="peer sr-only" wire:model.live="auto">
            <span class="absolute inset-0 bg-gray-200 rounded-full transition-colors peer-checked:bg-blue-600 dark:bg-neutral-700 dark:peer-checked:bg-blue-500"></span>
            <span class="absolute top-1/2 start-0.5 -translate-y-1/2 size-3 bg-white rounded-full shadow transition-transform peer-checked:translate-x-full dark:bg-neutral-400 dark:peer-checked:bg-white"></span>
        </label>


        <!-- Right-side label -->
        @if($auto)
            <span class="px-1.5 py-0 text-[0.8125rem]/5 font-medium text-white bg-suprimary border border-suprimary rounded shadow-md
                                        inline-flex items-center gap-1 truncate dark:bg-blue-500">
                {{__("On")}}
            </span>
        @else
            <span class="px-1.5 py-0 text-[0.8125rem]/5 font-medium text-white bg-red-600
                                        border border-red-600 rounded shadow-md inline-flex items-center gap-1 truncate">
                {{__("Off")}}
            </span>
        @endif
        @if($auto)
            {{__("Force language of subtitles")}}
            <!-- Force switch -->
            <label for="hs-xs-switch-force" class="relative inline-block w-8 h-4 cursor-pointer">
                <input type="checkbox" id="hs-xs-switch-force" class="peer sr-only" wire:model.live="force">
                <span class="absolute inset-0 bg-gray-200 rounded-full transition-colors peer-checked:bg-blue-600 dark:bg-neutral-700 dark:peer-checked:bg-blue-500"></span>
                <span class="absolute top-1/2 start-0.5 -translate-y-1/2 size-3 bg-white rounded-full shadow transition-transform peer-checked:translate-x-full dark:bg-neutral-400 dark:peer-checked:bg-white"></span>
            </label>

            <!-- select autosub language -->
                @if($force)
                    <select
                        name="autosub_language"
                        class="py-1 px-2 pe-6 border-gray-200 rounded-md text-xs bg-gray-50
                       focus:border-blue-500 focus:ring-blue-500
                       dark:bg-neutral-900 dark:border-neutral-700 dark:text-neutral-400">
                        <option value="en">{{__("English")}}</option>
                        <option value="sv">{{__("Swedish")}}</option>
                    </select>
                @endif

        @endif


    </div>
    @if($auto)
        <div class="mt-2 min-w-0 border border-gray-300 text-sm text-gray-700 rounded-lg p-4 sm:p-5 lg:p-6 dark:bg-yellow-600/[.15]">
            {{__("Subtitles will be autogenerated. You will receive an email when processing is complete. Since the subtitles are auto-generated, you should check the subtitles yourself and edit if necessary. ")}}
        </div>
    @endif
    <input type="hidden" name="autosub"  value="{{ $auto }}" >
@endif
