@if(count($savedfiles) < 1)
    <div class="rounded-lg border border-slate-200 bg-white p-4 dark:border-neutral-700 dark:bg-neutral-900">
        <div class="flex flex-wrap items-center gap-3">
            <span class="text-sm font-medium text-slate-900 dark:text-white">{{__("Generate subtitling")}}</span>
        <label for="hs-xs-switch-autosub" class="relative inline-block h-5 w-9 cursor-pointer">
            <input type="checkbox" id="hs-xs-switch-autosub" class="peer sr-only" wire:model.live="auto">
            <span class="absolute inset-0 rounded-full bg-slate-200 transition-colors peer-checked:bg-blue-600 dark:bg-neutral-700 dark:peer-checked:bg-blue-500"></span>
            <span class="absolute start-0.5 top-1/2 size-4 -translate-y-1/2 rounded-full bg-white shadow-sm transition-transform peer-checked:translate-x-full dark:bg-neutral-300 dark:peer-checked:bg-white"></span>
        </label>


        @if($auto)
            <span class="inline-flex items-center rounded-full border border-blue-200 bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700 dark:border-blue-900/70 dark:bg-blue-950 dark:text-blue-300">
                {{__("On")}}
            </span>
        @else
            <span class="inline-flex items-center rounded-full border border-red-200 bg-red-50 px-3 py-1 text-xs font-semibold text-red-700 dark:border-red-900/70 dark:bg-red-950 dark:text-red-300">
                {{__("Off")}}
            </span>
        @endif
        @if($auto)
            <span class="text-sm text-slate-700 dark:text-neutral-300">{{__("Force language of subtitles")}}</span>
            <label for="hs-xs-switch-force" class="relative inline-block h-5 w-9 cursor-pointer">
                <input type="checkbox" id="hs-xs-switch-force" class="peer sr-only" wire:model.live="force">
                <span class="absolute inset-0 rounded-full bg-slate-200 transition-colors peer-checked:bg-blue-600 dark:bg-neutral-700 dark:peer-checked:bg-blue-500"></span>
                <span class="absolute start-0.5 top-1/2 size-4 -translate-y-1/2 rounded-full bg-white shadow-sm transition-transform peer-checked:translate-x-full dark:bg-neutral-300 dark:peer-checked:bg-white"></span>
            </label>

                @if($force)
                    <select
                        name="autosub_language"
                        class="rounded-lg border-slate-300 bg-white px-3 py-2 pe-8 text-sm text-slate-900 shadow-sm focus:border-blue-500 focus:ring-blue-500 dark:border-neutral-700 dark:bg-neutral-950 dark:text-white">
                        <option value="en">{{__("English")}}</option>
                        <option value="sv">{{__("Swedish")}}</option>
                        @can('admin-content')
                            <option value="da">{{__("Danish")}}</option>
                            <option value="nl">{{__("Dutch")}}</option>
                            <option value="is">{{__("Icelandic")}}</option>
                            <option value="it">{{__("Italian")}}</option>
                            <option value="fi">{{__("Finnish")}}</option>
                            <option value="fr">{{__("French")}}</option>
                            <option value="de">{{__("German")}}</option>
                            <option value="no">{{__("Norwegian")}}</option>
                            <option value="ru">{{__("Russian")}}</option>
                            <option value="es">{{__("Spanish")}}</option>
                        @endcan
                    </select>
                @endif

        @endif
        </div>
    </div>
    @if($auto)
        <div class="mt-3 min-w-0 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900/70 dark:bg-amber-950/50 dark:text-amber-100">
            {{__("Subtitles will be autogenerated. You will receive an email when processing is complete. Since the subtitles are auto-generated, you should check the subtitles yourself and edit if necessary.")}}
        </div>
    @endif
    <input type="hidden" name="autosub"  value="{{ $auto }}" >
@endif
