@extends('layouts.suplay_upload')
@section('content')
    <form method="post" action="{{route('editpresentation', [$video, $editHandler])}}">
        @csrf
        @livewire('edit-presentation', [
        'video' => $video,
        'permissions' => $permissions,
        'individual_permissions' => $individual_permissions,
        'user_permission' => $user_permission
        ])
    </form>
    <div class="container px-3 px-sm-0">
        <div class="col-sm-12">

            <div class="rounded border shadow p-3 my-2">

                    @livewire('edit-autosubtitles', [
                    'video' => $video,
                    'presentation' => $editHandler])
                    <div class="form-group col-md-6 flex-column d-flex">
                        <div id="subtitleHolder">
                            <label class="form-control-label px-1">{{ __("Add a subtitle file") }}</label>
                            <form action="{{ route('subtitle-upload') }}" class="dropzone" id="subtitleupload">
                                <input type="file" name="subtitle"  style="display: none;">
                                <input type="hidden" name="subtitledir"  id="subtitledir" value="{{ $editHandler->local }}">
                                @csrf
                                <div class="dz-message" data-dz-message>
                                    <span>{{ __("Drop a WebVTT (.vtt) file here or click to browse") }}</span>
                                </div>
                            </form>
                        </div>
                        <!-- Auto subtile generation info -->
                        <div id="autoHolder" style="display: none;">
                            <label class="form-control-label px-1">{{ __("Autogeneration of subtitles") }}</label>
                            <div class="rounded border su-background__light p-3 my-2">
                                {{ __('Subtitles will be autogenerated. You will receive an email when processing is complete. Since the subtitles are auto-generated, you should check the subtitles yourself and edit if necessary.') }}
                            </div>
                        </div>
                    </div>


            </div>


        </div>
    </div>



    <script>
        Dropzone.discover();
        var deleteSubtitle = '{{ route("subtitle-delete") }}';
        var subtitledir =  document.getElementById('subtitledir').value;
        var token = '{!! csrf_token() !!}';

        let holder = document.getElementById('subtitleHolder');
        let holderinfo = document.getElementById('autoHolder');
        window.addEventListener('contentChanged', e => {
            if(e.detail.autosubs) {
                holder.style.display = 'none';
                holderinfo.style.display = 'block';
            }
            else {
                holder.style.display = 'block';
                holderinfo.style.display = 'none';
            }

        })
    </script>
@endsection

