@extends('layouts.suplay_upload')
@section('content')
    <form method="post" action="{{route('editpresentation', [$video, $editHandler])}}">
        @csrf
        @livewire('edit-presentation', [
        'video' => $video,
        'permissions' => $permissions,
        'individual_permissions' => $individual_permissions,
        'user_permission' => $user_permission,
        'presentation' => $editHandler
        ])

    <!-- disabled subtitling 2023-09-04 -->
    @if(app()->make('play_role') == 'Administrator')
            <div class="container px-3 px-sm-0">
                <div class="col-sm-12">
                    <div class="rounded border shadow p-3 my-2">
                        <div class="row justify-content-between text-left">
                            @livewire('edit-autosubtitles', [
                            'video' => $video,
                            'presentation' => $editHandler])
                        <!--Language toggle-->
                            <div id="sublanguageHolder" class="col">
                                <div class="form-group col-12 col-md-6 flex-column d-flex">
                                    <label for="subtitleLanguage" >{{__("Subtitle language:")}}</label>
                                    <select class="w-50 form-group form-control" name="subtitle_language" style="margin: 5px 0;">
                                        <option value="english">{{__("English")}}</option>
                                        <option value="swedish">{{__("Swedish")}}</option>
                                    </select>
                                </div>
                            </div>
    </form>
                                    <!-- end language toggle -->
                    </div>
                        <div class="form-group col-md-6 flex-column d-flex">
                            <div id="subtitleHolder">
                                <label class="form-control-label px-1">{{ __("Add a subtitle file") }}</label>
                                <form action="{{ route('subtitle-upload') }}" class="dropzone" id="subtitleupload">
                                    <input type="file" name="subtitle"  style="display: none;">
                                    <input type="hidden" name="subtitledir"  id="subtitledir" value="{{ $editHandler->local }}">
                                    @csrf
                                    <div class="dz-message" data-dz-message>
                                        <span>{{ __("Drop a WebVTT (.vtt) file here or click to browse") }}</span>
                                    </div>
                                </form>
                            </div>
                            <!-- Auto subtile generation info -->
                            <div id="autoHolder" style="display: none;">
                                <label class="form-control-label px-1">{{ __("Autogeneration of subtitles") }}</label>
                                <div class="rounded border su-background__light p-3 my-2">
                                    {{ __('Subtitles will be autogenerated. You will receive an email when processing is complete. Since the subtitles are auto-generated, you should check the subtitles yourself and edit if necessary.') }}
                                </div>
                                <label class="form-control-label px-1">{{ __("Force language of subtitles") }}</label>
                                @livewire('whisper-language', ['presentation' => $editHandler ])
                            </div>
                        </div>
                </div>
            </div>
        </div>
    @endif
    <!-- disabled subtitling 2023-09-04 -->
        <script>
            Dropzone.discover();
            var deleteSubtitle = '{{ route("subtitle-delete") }}';
            var subtitledir =  document.getElementById('subtitledir').value;
            var token = '{!! csrf_token() !!}';

            let holder = document.getElementById('subtitleHolder');
            let holderinfo = document.getElementById('autoHolder');
            let holderlanguage = document.getElementById('sublanguageHolder');
            window.addEventListener('contentChanged', e => {
                if(e.detail.autosubs) {
                    holder.style.display = 'none';
                    holderinfo.style.display = 'block';
                    holderlanguage.style.display = 'none';
                }
                else {
                    holder.style.display = 'block';
                    holderinfo.style.display = 'none';
                    holderlanguage.style.display = 'block';
                }

            })
        </script>
    @endsection

