<style>

    body {
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        background: #000;
    }

    p {
        margin: 50px;
        font-weight: 700;
        text-align: center;
        font-size: 40px;
        font-family: Hack, sans-serif;
        color: #fff;
        padding: 30px 30px;
        -moz-animation: cssAnimation 0s ease-in 10s forwards;
        /* Firefox */
        -webkit-animation: cssAnimation 0s ease-in 10s forwards;
        /* Safari and Chrome */
        -o-animation: cssAnimation 0s ease-in 10s forwards;
        /* Opera */
        animation: cssAnimation 0s ease-in 10s forwards;
        -webkit-animation-fill-mode: forwards;
        animation-fill-mode: forwards;
    }

    @keyframes cssAnimation {
        to {
            width:0;
            height:0;
            overflow:hidden;
        }
    }
    @-webkit-keyframes cssAnimation {
        to {
            width:0;
            height:0;
            visibility:hidden;
        }
    }
</style>

    <p><br>
        The subtitles provided herein have been automatically generated using advanced machine learning technology.
        While we strive for accuracy, it is important to note that automated processes may occasionally result in errors or inaccuracies.
        We recommend viewers exercise discretion and understand that these subtitles are not manually created or verified.
        The Department of Computer and Systems Sciences at Stockholm University shall not be held liable for any unintended misinterpretations, omissions, or discrepancies in the autogenerated subtitles.
        Thank you for your understanding and cooperation.
    </p>






